source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '10.0'

target 'FWMediaSDK_Example' do
  pod 'FWMediaSDK', :path => '../'
  
  target 'FWMediaSDK_Tests' do
    inherit! :search_paths

    
  end
end
